#!/bin/python3
#---- Script creado por Pavel Butzmann
#---- Obtencion de comandos en switch mediante python

import getpass
from datetime import date
from netmiko import ConnectHandler

today = date.today()
print("... Bienvenido al respaldo automatico de Routers Cisco  ...")
print("... Por favor verifica que la conexion sea mediante SSH ...")
target = input("IP address: ") # Se solicita al usuario ingresar la direccion IP
print("SSH Login")
user = input("User: ") # se solicita usuario con el que se puede ingresar al dispositivo
passw = getpass.getpass() #Solicita password para entrar al dispositivo sin mostrar los caracteres


iou1 = {
'device_type': 'cisco_ios',
'ip': target,
'username': user,
'password': passw,
}


device = ConnectHandler(**iou1) # Conexion al dispositivo

print("Se establecio la conexion con el dispositivo...")

output0 = device.send_command("show run | include hostname")
output1 = device.send_command("show running-config")
output2 = device.send_command("show version")
output3 = device.send_command("show inventory")
output4 = device.send_command("show module")
output5 = device.send_command("show interfaces status")
output6 = device.send_command("show interfaces")
output7 = device.send_command("show interfaces | incl error")
output8 = device.send_command("show interfaces | incl broadcast")
output9 = device.send_command("show interfaces description")
output10 = device.send_command("show ip interface brief")
output11 = device.send_command("show vlan")
output12 = device.send_command("show arp")
output13 = device.send_command("show mac address-table")
output14 = device.send_command("show ip route")
output15 = device.send_command("show ip protocols")
output16 = device.send_command("show ip bgp")
output17 = device.send_command("show ip bgp neighbors")
output18 = device.send_command("show ip bgp summary")
output19 = device.send_command("show ip eigrp neighbors")
output20 = device.send_command("show ip ospf neighbors")
output21 = device.send_command("show ip ospf database")
output22 = device.send_command("show ip cef")
output23 = device.send_command("show cdp neighbors")
output24 = device.send_command("show cdp neighbors detail")
output25 = device.send_command("show lldp neighbors")
output26 = device.send_command("show lldp neighbors detail")
output27 = device.send_command("show logging")
output28 = device.send_command("show startup-config")

print("Se procede a la generacion del archivo...")
print("el archivo se guarda como:" + ((output0[9::])+"-backup-"+str(today)+".txt"))

save_file = open((output0[9::])+"-backup-"+str(today)+".txt","w")
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *          SHOW RUNNING CONFIG        * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output1)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *            SHOW VERSION             * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output2)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *           SHOW INVENTORY            * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output3)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *             SHOW MODULE             * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output4)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *       SHOW INTERFACE STATUS         * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output5)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *           SHOW INTERFACES            * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output6)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *    SHOW INTERFACES | INCLUDE ERROR  * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output7)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n * SHOW INTERFACES | INCLUDE BROADCAST * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output8)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *     SHOW INTERFACES DESCRIPTION     * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output9)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *       SHOW IP INTERFACE BRIEF       * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output10)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *               SHOW VLAN             * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output11)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *               SHOW ARP              * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output12)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *       SHOW MAC ADDRESS-TABLE        * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output13)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *           SHOW IP ROUTE             * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output14)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *          SHOW IP PROTOCOLS          * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output15)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *             SHOW IP BGP             * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output16)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *        SHOW IP BGP NEIGHBORS        * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output17)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *         SHOW IP BGP SUMMARY         * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output18)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *       SHOW IP EIGRP NEIGHBORS       * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output19)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *        SHOW IP OSPF NEIGHBORS       * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output20)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *       SHOW IP OSPF DATABASE         * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output21)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *            SHOW IP CEF              * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output22)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *         SHOW CDP NEIGHBORS          * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output23)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *      SHOW CDP NEIGHBORS DETAIL      * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output24)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *         SHOW LLDP NEIGHBORS         * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output25)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *      SHOW LLDP NEIGHBORS DETAIL     * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output26)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *            SHOW LOGGING             * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output27)
save_file.write("\n\n\n --------------------------------------- \n")
save_file.write("\n *         SHOW STARTUP-CONFIG         * \n")
save_file.write("\n --------------------------------------- \n")
save_file.write(output28)


save_file.close() # Se guarda el documento en la misma ruta donde se ejecuta el programa
device.disconnect() # desconexion del dispositivo
